//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApplication2.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WindowsFormsApplication2.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap _2000px_Diving_pictogram_svg {
            get {
                object obj = ResourceManager.GetObject("2000px-Diving_pictogram.svg", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap _2000px_Diving_pictogram1 {
            get {
                object obj = ResourceManager.GetObject("2000px-Diving_pictogram1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap _2000px_Diving_pictogram2 {
            get {
                object obj = ResourceManager.GetObject("2000px-Diving_pictogram2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap _2000px_Diving_pictogram3 {
            get {
                object obj = ResourceManager.GetObject("2000px-Diving_pictogram3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap _2000px_Diving_pictogram4 {
            get {
                object obj = ResourceManager.GetObject("2000px-Diving_pictogram4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap admin_icon {
            get {
                object obj = ResourceManager.GetObject("admin-icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap AdminMeny {
            get {
                object obj = ResourceManager.GetObject("AdminMeny", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Aha_Soft_Free_Large_Boss_Judge {
            get {
                object obj = ResourceManager.GetObject("Aha-Soft-Free-Large-Boss-Judge", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Aha_Soft_Free_Large_Boss_Judge1 {
            get {
                object obj = ResourceManager.GetObject("Aha-Soft-Free-Large-Boss-Judge1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap c724df86_834f_4035_b852_f0c5e3a3411a {
            get {
                object obj = ResourceManager.GetObject("c724df86-834f-4035-b852-f0c5e3a3411a", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap c724df86_834f_4035_b852_f0c5e3a3411a1 {
            get {
                object obj = ResourceManager.GetObject("c724df86-834f-4035-b852-f0c5e3a3411a1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap CancelIcon {
            get {
                object obj = ResourceManager.GetObject("CancelIcon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap CheckMarkIcon {
            get {
                object obj = ResourceManager.GetObject("CheckMarkIcon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap HelpWindowBild {
            get {
                object obj = ResourceManager.GetObject("HelpWindowBild", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kjell;drejjgon
        ///Tomas;MyHorse
        ///Funky;Slipknot
        ///dipsauce;ducksauce
        ///;.
        /// </summary>
        public static string Inloggning {
            get {
                return ResourceManager.GetString("Inloggning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Judge_icon {
            get {
                object obj = ResourceManager.GetObject("Judge-icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap judgePic {
            get {
                object obj = ResourceManager.GetObject("judgePic", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to asdffef
        ///appor
        ///.
        /// </summary>
        public static string ListOfContest {
            get {
                return ResourceManager.GetString("ListOfContest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 100A;0.5
        ///100B;0.4
        ///101A;0.6
        ///101B;0.7
        ///102A;0.9
        ///102B;0.8
        ///200A;0.2
        ///200B;0.1
        ///201A;0.4
        ///201B;0.6
        ///202A;0.5
        ///202B;0.3
        ///300A;0.4
        ///300B;0.7
        ///301A;0.8
        ///301B;0.3
        ///302A;1
        ///302B;0.9.
        /// </summary>
        public static string ListOfJump {
            get {
                return ResourceManager.GetString("ListOfJump", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap LoggaInBild {
            get {
                object obj = ResourceManager.GetObject("LoggaInBild", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap SubmitJudgeScore {
            get {
                object obj = ResourceManager.GetObject("SubmitJudgeScore", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Swimiing_pools {
            get {
                object obj = ResourceManager.GetObject("Swimiing-pools", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Swimiing_pools1 {
            get {
                object obj = ResourceManager.GetObject("Swimiing-pools1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Swimiing_pools2 {
            get {
                object obj = ResourceManager.GetObject("Swimiing-pools2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Swimiing_pools3 {
            get {
                object obj = ResourceManager.GetObject("Swimiing-pools3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap swimming_pool_icon_png_3 {
            get {
                object obj = ResourceManager.GetObject("swimming-pool-icon-png-3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap swimming_pool_icon_png_3___kopia {
            get {
                object obj = ResourceManager.GetObject("swimming-pool-icon-png-3 - kopia", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap swimming_pool_icon_png_3___kopia1 {
            get {
                object obj = ResourceManager.GetObject("swimming-pool-icon-png-3 - kopia1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap swimming_pool_icon_png_3___kopia2 {
            get {
                object obj = ResourceManager.GetObject("swimming-pool-icon-png-3 - kopia2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap swimming_pool_icon_png_31 {
            get {
                object obj = ResourceManager.GetObject("swimming-pool-icon-png-31", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap swimming_pool_icon_png_32 {
            get {
                object obj = ResourceManager.GetObject("swimming-pool-icon-png-32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap swimming_pool_icon_png_33 {
            get {
                object obj = ResourceManager.GetObject("swimming-pool-icon-png-33", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
